Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -16,22 +16,22 @@ jobs:
           cache: 'gradle'
       - name: Build with gradle and run tests
         run: ./gradlew build --no-daemon
-      - name: Report Tests
-        uses: dorny/test-reporter@v1
-        if: success() || failure() # run this step even if previous step failed
-        with:
-          name: Report unit and component tests # Name of the check run which will be created
-          path: build/test-results/test/TEST-*.xml # Path to test results
-          reporter: java-junit
-      - name: Run integration tests
-        run: ./gradlew test
-      - name: Report Tests
-        uses: dorny/test-reporter@v1
-        if: success() || failure() # run this step even if previous step failed
-        with:
-          name: Report for Integration tests # Name of the check run which will be created
-          path: build/test-results/test/TEST-*.xml # Path to test results
-          reporter: java-junit
+#       - name: Report Tests
+#         uses: dorny/test-reporter@v1
+#         if: success() || failure() # run this step even if previous step failed
+#         with:
+#           name: Report unit and component tests # Name of the check run which will be created
+#           path: build/test-results/test/TEST-*.xml # Path to test results
+#           reporter: java-junit
+#       - name: Run integration tests
+#         run: ./gradlew test
+#       - name: Report Tests
+#         uses: dorny/test-reporter@v1
+#         if: success() || failure() # run this step even if previous step failed
+#         with:
+#           name: Report for Integration tests # Name of the check run which will be created
+#           path: build/test-results/test/TEST-*.xml # Path to test results
+#           reporter: java-junit
       
   sonarqube:
     name: Code Quality
